### ISSUE TITLE
[Feature request]: Fill the width of the page on video lists

### ISSUE THREAD

**Issue by Aggnog** [sapondanaisriwan/AdashimaaTube#125]
### Describe the change you'd like

The layout reduces the size of the videos display area instead of stretching to the width of the screen, making half of the space unused. 

On 21:9 it's very bad https://i.imgur.com/iEwQQM7.png
But on a regular screen it's still bad https://i.imgur.com/GoyRUlX.png

The new official yt design only shows 6 videos wide on both 16:9 and 21:9 so on 21:9 it looks like this with huge gaps https://i.imgur.com/DoOcy8f.png, which is why I'm looking for a fix at all. But I think this style should also fill the page or have that option.

**Comment by sapondanaisriwan** [comment]
I think the best way to fix this is use [row-fixer](https://chrome.google.com/webstore/detail/youtube-row-fixer/kehjfphhkfppnnjhdfhanmehkegdppho) because your screen is very wide. Anyway I'll find out how to fix this using CSS.
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/519330a1-02a7-498d-9e9a-a78634dbb27e)

**Comment by sapondanaisriwan** [comment]
https://github.com/sapondanaisriwan/AdashimaaTube/issues/122

**Comment by sapondanaisriwan** [comment]
![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/cef7c12e-d71c-41f9-af00-c6a5c9ed16d7)
